import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/app/nav';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-row m-20 gap-20">
          <Nav />
            <div className="flex flex-col flex-1 border-2 border-amber-950">
                {children}
            </div>
        </main>
      </body>
    </html>
  )
}
